[project]
name = "panel-training"
version = "0.1.0"
description = "Panel training notebooks and examples."
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = "3.13.*"
aiohttp = "*"
altair = "*"
bokeh = "*"
holoviews = "*"
hvplot = "*"
ipykernel = "*"
jupyter-bokeh = "*"
jupyterlab = "*"
jupyterlab-myst = "*"
lumen = "*"
numpy = "*"
pandas = "*"
panel = "*"
param = "*"
pyarrow = "*"
pyparsing = "*"

[pypi-dependencies]
panel-material-ui = "*"

[tasks]
lab = "jupyter lab"
notebook = "jupyter lab"
